import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common"
import { Prisma, SupportAgentLevel, SupportAgentStatus, SupportLiveChatStatus, SupportMessageSenderKind, WalletTransactionSourceType } from "@prisma/client"
import { randomUUID } from "node:crypto"

import { PrismaService } from "../../prisma.service"
import { CreditWalletTransaction } from "../economy/transactions/credit-wallet-transaction"
import { DebitWalletTransaction } from "../economy/transactions/debit-wallet-transaction"
import { NotificationsService } from "../notifications/notifications.service"
import { LiveChatListQueryDto, LiveChatMessageDto, LiveChatRefundDto, LiveChatStatusUpdateDto, StartLiveChatDto, UpdateSupportConfigurationDto } from "./dtos"

const ACTIVE_STATUSES = [SupportLiveChatStatus.QUEUED, SupportLiveChatStatus.ASSIGNED, SupportLiveChatStatus.ACTIVE, SupportLiveChatStatus.PAUSED, SupportLiveChatStatus.WAITING_FOR_PLAYER]

@Injectable()
export class SupportLiveChatService {
  constructor(private readonly prisma: PrismaService, private readonly credit: CreditWalletTransaction, private readonly debit: DebitWalletTransaction, private readonly notifications: NotificationsService) {}

  async quote(playerId: string) {
    const config = await this.config()
    if (!config.enabled || !config.liveChatEnabled) throw new ForbiddenException("Live support chat is currently unavailable")
    const dayStart = new Date(); dayStart.setUTCHours(0, 0, 0, 0)
    const todayCount = await this.prisma.supportLiveChatSession.count({ where: { playerId, createdAt: { gte: dayStart } } })
    if (todayCount >= config.playerLiveChatRatePerDay) throw new ConflictException("Daily live-support limit reached; try again tomorrow")
    const [availableAgents, queued, active] = await Promise.all([
      this.prisma.supportAgent.count({ where: { revokedAt: null, status: SupportAgentStatus.AVAILABLE } }),
      this.prisma.supportLiveChatSession.count({ where: { status: SupportLiveChatStatus.QUEUED } }),
      this.prisma.supportLiveChatSession.findFirst({ where: { playerId, status: { in: ACTIVE_STATUSES } }, select: { id: true, sessionNumber: true } }),
    ])
    if (active) throw new ConflictException("You already have an active live support chat")
    const expiresAt = new Date(Date.now() + 2 * 60 * 1000)
    const estimatedWaitSeconds = availableAgents > 0 ? 30 : Math.min((queued + 1) * 120, 3600)
    const quote = await this.prisma.supportLiveChatQuote.create({ data: { playerId, priceGld: config.liveChatPriceGld, currencyCode: config.liveChatCurrencyCode, availableAgents, estimatedWaitSeconds, expiresAt } })
    return { quoteId: quote.id, priceGld: quote.priceGld.toString(), currencyCode: quote.currencyCode, availableAgents, estimatedWaitSeconds, expiresAt: quote.expiresAt, expiresInSeconds: 120 }
  }

  async start(playerId: string, dto: StartLiveChatDto) {
    const existing = await this.prisma.supportLiveChatSession.findUnique({ where: { playerId_purchaseIdempotencyKey: { playerId, purchaseIdempotencyKey: dto.idempotencyKey } } })
    if (existing) return this.get(playerId, existing.id)
    const config = await this.config()
    if (!config.enabled || !config.liveChatEnabled) throw new ForbiddenException("Live support chat is currently unavailable")
    const quote = await this.prisma.supportLiveChatQuote.findUnique({ where: { id: dto.quoteId } })
    if (!quote || quote.playerId !== playerId) throw new BadRequestException("Live-chat quote is invalid")
    if (quote.usedAt || quote.expiresAt.getTime() <= Date.now()) throw new ConflictException("Live-chat quote has expired")
    const queueSize = await this.prisma.supportLiveChatSession.count({ where: { status: SupportLiveChatStatus.QUEUED } })
    if (queueSize >= config.maxLiveChatQueueSize) throw new ConflictException("Live-chat queue is currently full")
    const sessionId = randomUUID()
    const session = await this.prisma.$transaction(async (tx) => {
      const claimedQuote = await tx.supportLiveChatQuote.updateMany({ where: { id: quote.id, usedAt: null, expiresAt: { gt: new Date() } }, data: { usedAt: new Date() } })
      if (!claimedQuote.count) throw new ConflictException("Live-chat quote has already been used")
      const created = await tx.supportLiveChatSession.create({ data: { id: sessionId, sessionNumber: this.sessionNumber(), playerId, quoteId: quote.id, purchaseIdempotencyKey: dto.idempotencyKey, status: SupportLiveChatStatus.PAYMENT_PENDING, quotedPriceGld: quote.priceGld, chargedAmountGld: quote.priceGld, currencyCode: quote.currencyCode, configurationVersion: config.updatedAt.toISOString() } })
      const debit = await this.debit.runWithinTransaction({ userId: playerId, currencyCode: quote.currencyCode, amount: BigInt(quote.priceGld.floor().toFixed(0)), amountDecimal: quote.priceGld.toString(), sourceId: sessionId, sourceType: WalletTransactionSourceType.SYSTEM, metadata: { reason: "SUPPORT_LIVE_CHAT", quoteId: quote.id, sessionNumber: created.sessionNumber } }, tx)
      const ledger = await tx.walletTransaction.findUnique({ where: { grantKey: `SYSTEM:${sessionId}:${playerId}:${quote.currencyCode}` }, select: { id: true } })
      await tx.supportLiveChatCharge.create({ data: { sessionId, amountGld: quote.priceGld, currencyCode: quote.currencyCode, ledgerId: ledger?.id, quoteId: quote.id } })
      await tx.supportLiveChatEvent.createMany({ data: [{ sessionId, actorId: playerId, type: "CREATED", metadata: { quoteId: quote.id } }, { sessionId, actorId: playerId, type: "PAYMENT_CHARGED", metadata: { amountGld: quote.priceGld.toString(), ledgerId: ledger?.id } }] })
      return tx.supportLiveChatSession.update({ where: { id: created.id }, data: { status: SupportLiveChatStatus.QUEUED, walletLedgerId: ledger?.id }, include: { charge: true } })
    })
    await this.notifyAvailableAgents(session.id, `Live chat ${session.sessionNumber} is waiting`, "A player paid for live support and is waiting for an agent.", "support.live-chat.queued")
    return this.serialize(session)
  }

  async listPlayer(playerId: string, query: LiveChatListQueryDto) {
    const rows = await this.prisma.supportLiveChatSession.findMany({ where: { playerId, ...(query.status ? { status: query.status as SupportLiveChatStatus } : {}) }, include: { assignedAgent: { include: { user: { select: { username: true } } } }, messages: { orderBy: { sequence: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: query.limit, skip: query.offset })
    return rows.map((row) => this.serialize(row))
  }

  async get(userId: string, sessionId: string, includeInternal = false) {
    const row = await this.getRaw(sessionId, includeInternal)
    await this.authorize(userId, row)
    return this.serialize(row, includeInternal)
  }

  async sendPlayerMessage(userId: string, sessionId: string, dto: LiveChatMessageDto) { const row = await this.getRaw(sessionId); await this.authorize(userId, row); return this.addMessage(row, userId, SupportMessageSenderKind.PLAYER, dto, false) }
  async sendAgentMessage(userId: string, sessionId: string, dto: LiveChatMessageDto, internal = false) { const agent = await this.requireAgent(userId); const row = await this.getRaw(sessionId); if (row.assignedAgentId !== agent.id && agent.level !== SupportAgentLevel.SUPERVISOR) throw new ForbiddenException("Claim this live chat before replying"); return this.addMessage(row, userId, SupportMessageSenderKind.AGENT, dto, internal) }

  async markRead(userId: string, sessionId: string, sequence: number) { const row = await this.getRaw(sessionId); await this.authorize(userId, row); await this.prisma.supportLiveChatRead.upsert({ where: { sessionId_userId: { sessionId, userId } }, create: { sessionId, userId, lastSequence: sequence }, update: { lastSequence: sequence } }); return { updated: true } }

  async cancel(playerId: string, sessionId: string) { const row = await this.getRaw(sessionId); if (row.playerId !== playerId) throw new ForbiddenException("This is not your live chat"); const cancellable: SupportLiveChatStatus[] = [SupportLiveChatStatus.QUEUED, SupportLiveChatStatus.PAYMENT_PENDING]; if (!cancellable.includes(row.status)) throw new ConflictException("Only a waiting live chat can be cancelled"); await this.endStatus(row, SupportLiveChatStatus.ENDED, playerId); const config = await this.config(); if (config.refundOnAgentCancellation) await this.refundInternal(sessionId, "Player cancelled before assignment"); return this.get(playerId, sessionId) }
  async end(userId: string, sessionId: string) { const row = await this.getRaw(sessionId); await this.authorize(userId, row); await this.endStatus(row, SupportLiveChatStatus.ENDED, userId); return this.get(userId, sessionId, await this.isAdmin(userId)) }

  async agentMe(userId: string) { const agent = await this.requireAgent(userId); const active = await this.prisma.supportLiveChatSession.count({ where: { assignedAgentId: agent.id, status: { in: [SupportLiveChatStatus.ASSIGNED, SupportLiveChatStatus.ACTIVE, SupportLiveChatStatus.PAUSED, SupportLiveChatStatus.WAITING_FOR_PLAYER] } } }); return { id: agent.id, level: agent.level, status: agent.status, maxConcurrentLiveChats: agent.maxConcurrentLiveChats, activeLiveChats: active } }
  async agentQueue(userId: string, query: LiveChatListQueryDto) { await this.requireAgent(userId); const rows = await this.prisma.supportLiveChatSession.findMany({ where: { ...(query.status ? { status: query.status as SupportLiveChatStatus } : { status: { in: [SupportLiveChatStatus.QUEUED, SupportLiveChatStatus.ASSIGNED, SupportLiveChatStatus.ACTIVE, SupportLiveChatStatus.WAITING_FOR_PLAYER] } }) }, include: { player: { select: { id: true, username: true, firstName: true, lastName: true } }, assignedAgent: { include: { user: { select: { username: true } } } }, messages: { orderBy: { sequence: "desc" }, take: 1 } }, orderBy: { queueEnteredAt: "asc" }, take: query.limit, skip: query.offset }); return rows.map((row) => this.serialize(row)) }
  async claim(userId: string, sessionId: string) { const agent = await this.requireAgent(userId); const config = await this.config(); const count = await this.prisma.supportLiveChatSession.count({ where: { assignedAgentId: agent.id, status: { in: [SupportLiveChatStatus.ASSIGNED, SupportLiveChatStatus.ACTIVE, SupportLiveChatStatus.PAUSED, SupportLiveChatStatus.WAITING_FOR_PLAYER] } } }); if (count >= agent.maxConcurrentLiveChats) throw new ConflictException("Your live-chat capacity is full"); const updated = await this.prisma.$transaction(async (tx) => { const claimed = await tx.supportLiveChatSession.updateMany({ where: { id: sessionId, assignedAgentId: null, status: SupportLiveChatStatus.QUEUED }, data: { assignedAgentId: agent.id, status: SupportLiveChatStatus.ASSIGNED, assignedAt: new Date(), lastActivityAt: new Date() } }); if (!claimed.count) throw new ConflictException("This live chat has already been claimed"); await tx.supportLiveChatEvent.create({ data: { sessionId, actorId: userId, type: "ASSIGNED", metadata: { agentId: agent.id } } }); return tx.supportLiveChatSession.findUnique({ where: { id: sessionId } }) }); if (!updated) throw new NotFoundException("Live chat not found"); await this.notifyPlayer(updated.id, "A support agent joined your live chat", "Your live chat is ready.", "support.live-chat.assigned", config.pushNotificationsEnabled); return this.get(userId, sessionId, true) }
  async updateAgentStatus(userId: string, status: SupportAgentStatus) { const agent = await this.requireAgent(userId); const updated = await this.prisma.supportAgent.update({ where: { id: agent.id }, data: { status, lastSeenAt: new Date() } }); return { id: updated.id, status: updated.status, level: updated.level } }
  async updateStatus(userId: string, sessionId: string, dto: LiveChatStatusUpdateDto, admin = false) { const nextStatus = dto.status as SupportLiveChatStatus; if (!([SupportLiveChatStatus.ASSIGNED, SupportLiveChatStatus.ACTIVE, SupportLiveChatStatus.PAUSED, SupportLiveChatStatus.WAITING_FOR_PLAYER, SupportLiveChatStatus.ENDED] as SupportLiveChatStatus[]).includes(nextStatus)) throw new ConflictException("Use the refund action for financial status changes"); if (admin) await this.requireAdmin(userId); const row = await this.getRaw(sessionId); if (!admin) { const agent = await this.requireAgent(userId); if (row.assignedAgentId !== agent.id && agent.level !== SupportAgentLevel.SUPERVISOR) throw new ForbiddenException("You are not assigned to this live chat") } await this.endStatus(row, nextStatus, userId); return this.get(userId, sessionId, true) }

  async adminList(query: LiveChatListQueryDto) { const rows = await this.prisma.supportLiveChatSession.findMany({ where: query.status ? { status: query.status as SupportLiveChatStatus } : undefined, include: { player: { select: { id: true, username: true } }, assignedAgent: { include: { user: { select: { username: true } } } }, charge: true, refund: true, messages: { orderBy: { sequence: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: query.limit, skip: query.offset }); return rows.map((row) => this.serialize(row, true)) }
  async adminRefund(adminId: string, sessionId: string, dto: LiveChatRefundDto) { await this.requireAdmin(adminId); await this.refundInternal(sessionId, dto.reason); return this.get(adminId, sessionId, true) }
  async runNoAgentRefunds(adminId: string) { await this.requireAdmin(adminId); const config = await this.config(); if (!config.refundOnNoAgentConnection) return { refunded: 0 }; const cutoff = new Date(Date.now() - config.liveChatGraceMinutes * 60 * 1000); const rows = await this.prisma.supportLiveChatSession.findMany({ where: { status: SupportLiveChatStatus.QUEUED, queueEnteredAt: { lt: cutoff } }, select: { id: true } }); let refunded = 0; for (const row of rows) { try { await this.refundInternal(row.id, "No agent connected within the configured guarantee window"); refunded += 1 } catch (_) { /* another worker or an admin may have handled it */ } } return { refunded } }

  async authorizeSocket(userId: string, sessionId: string) { const row = await this.getRaw(sessionId); await this.authorize(userId, row); return row }
  async socketTypingAllowed(userId: string, sessionId: string) { await this.authorizeSocket(userId, sessionId); return true }

  private async addMessage(row: any, senderId: string, senderKind: SupportMessageSenderKind, dto: LiveChatMessageDto, internal: boolean) { const existing = await this.prisma.supportLiveChatMessage.findFirst({ where: { sessionId: row.id, clientMessageId: dto.clientMessageId } }); if (existing) return this.get(senderId, row.id, senderKind === SupportMessageSenderKind.AGENT); if ([SupportLiveChatStatus.ENDED, SupportLiveChatStatus.REFUNDED, SupportLiveChatStatus.EXPIRED].includes(row.status)) throw new ConflictException("This live chat has ended"); const config = await this.config(); const recent = await this.prisma.supportLiveChatMessage.count({ where: { sessionId: row.id, senderId, createdAt: { gte: new Date(Date.now() - 60_000) } } }); if (senderKind === SupportMessageSenderKind.AGENT && recent >= config.agentReplyRatePerMinute) throw new ConflictException("Reply rate limit reached"); let body = dto.body.trim(); if (config.profanityPolicy === "BLOCK" && this.hasBlockedWords(body)) throw new BadRequestException("Please remove abusive language before sending"); if (config.profanityPolicy === "REDACT") body = this.redact(body); if (!body || body.length > config.maxMessageLength) throw new BadRequestException(`Message must be between 1 and ${config.maxMessageLength} characters`); await this.prisma.$transaction(async (tx) => { const next = await tx.supportLiveChatSession.update({ where: { id: row.id }, data: { lastActivityAt: new Date(), lastSequence: { increment: 1 } as never } }).catch(async () => { const current = await tx.supportLiveChatMessage.count({ where: { sessionId: row.id } }); return tx.supportLiveChatSession.update({ where: { id: row.id }, data: { lastActivityAt: new Date() } }).then(() => ({ lastSequence: current + 1 })) }); await tx.supportLiveChatMessage.create({ data: { sessionId: row.id, senderId, senderKind, sequence: (next as any).lastSequence, clientMessageId: dto.clientMessageId, body, internal } }); await tx.supportLiveChatEvent.create({ data: { sessionId: row.id, actorId: senderId, type: "MESSAGE_ADDED", metadata: { sequence: (next as any).lastSequence } } }) }); if (senderKind === SupportMessageSenderKind.PLAYER && row.assignedAgentId) await this.notifyAgent(row.assignedAgentId, row.id, "Player replied in live chat", body, "support.live-chat.message.received"); if (senderKind === SupportMessageSenderKind.AGENT && !internal) await this.notifyPlayer(row.id, "Support replied in live chat", body, "support.live-chat.message.received", config.pushNotificationsEnabled); return this.get(senderId, row.id, senderKind === SupportMessageSenderKind.AGENT) }

  private async endStatus(row: any, status: SupportLiveChatStatus, actorId: string) { await this.prisma.$transaction(async (tx) => { const ended: SupportLiveChatStatus[] = [SupportLiveChatStatus.ENDED, SupportLiveChatStatus.REFUNDED, SupportLiveChatStatus.EXPIRED]; const eventType = status === SupportLiveChatStatus.ENDED ? "ENDED" : status === SupportLiveChatStatus.ACTIVE ? "STARTED" : status === SupportLiveChatStatus.PAUSED || status === SupportLiveChatStatus.WAITING_FOR_PLAYER ? "PAUSED" : status === SupportLiveChatStatus.ASSIGNED ? "ASSIGNED" : "RESUMED"; await tx.supportLiveChatSession.update({ where: { id: row.id }, data: { status, startedAt: status === SupportLiveChatStatus.ACTIVE ? new Date() : undefined, endedAt: ended.includes(status) ? new Date() : undefined, lastActivityAt: new Date() } }); await tx.supportLiveChatEvent.create({ data: { sessionId: row.id, actorId, type: eventType as any } }) }) }
  private async refundInternal(sessionId: string, reason: string) { const config = await this.config(); const row = await this.prisma.supportLiveChatSession.findUnique({ where: { id: sessionId }, include: { refund: true } }); if (!row) throw new NotFoundException("Live chat not found"); if (row.refund) return row.refund; if (row.chargedAmountGld.lte(0)) throw new ConflictException("Live chat was not charged"); return this.prisma.$transaction(async (tx) => { const credit = await this.credit.runWithinTransaction({ userId: row.playerId, currencyCode: row.currencyCode, amount: BigInt(row.chargedAmountGld.floor().toFixed(0)), amountDecimal: row.chargedAmountGld.toString(), sourceId: `support-live-refund:${row.id}`, sourceType: WalletTransactionSourceType.REFUND, rewardGrantKey: `support-live-refund:${row.id}:${row.playerId}`, metadata: { reason: "SUPPORT_LIVE_CHAT_REFUND", sessionId: row.id, refundReason: reason } }, tx); const ledger = await tx.walletTransaction.findUnique({ where: { grantKey: `REFUND:support-live-refund:${row.id}:${row.playerId}:${row.currencyCode}` }, select: { id: true } }); const refund = await tx.supportLiveChatRefund.create({ data: { sessionId: row.id, amountGld: row.chargedAmountGld, currencyCode: row.currencyCode, ledgerId: ledger?.id, reason } }); await tx.supportLiveChatSession.update({ where: { id: row.id }, data: { status: SupportLiveChatStatus.REFUNDED, refundLedgerId: ledger?.id, endedAt: new Date() } }); await tx.supportLiveChatEvent.create({ data: { sessionId: row.id, type: "REFUNDED", metadata: { reason, ledgerId: ledger?.id } } }); return refund }) }
  private async getRaw(id: string, includeInternal = false) { const row = await this.prisma.supportLiveChatSession.findUnique({ where: { id }, include: { player: { select: { id: true, username: true, firstName: true, lastName: true } }, assignedAgent: { include: { user: { select: { id: true, username: true } } } }, charge: true, refund: true, messages: { where: includeInternal ? undefined : { internal: false }, orderBy: { sequence: "asc" } } } }); if (!row) throw new NotFoundException("Live chat not found"); return row }
  private async authorize(userId: string, row: any) { if (row.playerId === userId) return; const admin = await this.isAdmin(userId); if (admin) return; const agent = await this.prisma.supportAgent.findUnique({ where: { userId } }); if (!agent || agent.revokedAt || agent.status === SupportAgentStatus.SUSPENDED || (row.assignedAgentId !== agent.id && agent.level !== SupportAgentLevel.SUPERVISOR)) throw new ForbiddenException("You cannot access this live chat") }
  private async requireAgent(userId: string) { const agent = await this.prisma.supportAgent.findUnique({ where: { userId } }); if (!agent || agent.revokedAt || agent.status === SupportAgentStatus.SUSPENDED) throw new ForbiddenException("Support agent access is required"); return agent }
  private async requireAdmin(userId: string) { if (!(await this.isAdmin(userId))) throw new ForbiddenException("System administrator access is required") }
  private async isAdmin(userId: string) { const user = await this.prisma.user.findUnique({ where: { id: userId }, select: { isSystemAdmin: true } }); return Boolean(user?.isSystemAdmin) }
  private async config() { const row = await this.prisma.supportConfiguration.findUnique({ where: { key: "default" } }); if (!row) throw new NotFoundException("Support configuration is missing"); return row }
  private async notifyAvailableAgents(sessionId: string, title: string, body: string, type: string) { const agents = await this.prisma.supportAgent.findMany({ where: { revokedAt: null, status: { in: [SupportAgentStatus.AVAILABLE, SupportAgentStatus.BUSY] } }, select: { userId: true } }); for (const agent of agents) await this.notifications.createSupportNotification({ recipientId: agent.userId, route: `/support/live-chats/${sessionId}`, extraData: { sessionId }, notificationType: type, title, body, enabled: true, pushEnabled: true }) }
  private async notifyAgent(agentId: string, sessionId: string, title: string, body: string, type: string) { const agent = await this.prisma.supportAgent.findUnique({ where: { id: agentId } }); if (agent) await this.notifications.createSupportNotification({ recipientId: agent.userId, route: `/support/live-chats/${sessionId}`, extraData: { sessionId }, notificationType: type, title, body, enabled: true, pushEnabled: true }) }
  private async notifyPlayer(sessionId: string, title: string, body: string, type: string, pushEnabled = true) { const row = await this.prisma.supportLiveChatSession.findUnique({ where: { id: sessionId }, select: { playerId: true } }); if (row) await this.notifications.createSupportNotification({ recipientId: row.playerId, route: `/support/live-chats/${sessionId}`, extraData: { sessionId }, notificationType: type, title, body, enabled: true, pushEnabled }) }
  private serialize(row: any, includeInternal = false) { return { id: row.id, sessionNumber: row.sessionNumber, playerId: row.playerId, status: row.status, quotedPriceGld: row.quotedPriceGld?.toString(), chargedAmountGld: row.chargedAmountGld?.toString(), currencyCode: row.currencyCode, assignedAgent: row.assignedAgent ? { id: row.assignedAgent.id, username: row.assignedAgent.user?.username } : null, player: row.player ? { id: row.player.id, username: row.player.username, name: [row.player.firstName, row.player.lastName].filter(Boolean).join(" ") || row.player.username } : undefined, queueEnteredAt: row.queueEnteredAt, assignedAt: row.assignedAt, startedAt: row.startedAt, endedAt: row.endedAt, lastActivityAt: row.lastActivityAt, unread: false, messages: row.messages?.filter((message: any) => includeInternal || !message.internal).map((message: any) => ({ id: message.id, sequence: message.sequence, body: message.body, senderKind: message.senderKind, internal: includeInternal ? message.internal : undefined, createdAt: message.createdAt })) ?? [], charge: row.charge ? { amountGld: row.charge.amountGld.toString(), ledgerId: row.charge.ledgerId } : null, refund: row.refund ? { amountGld: row.refund.amountGld.toString(), reason: row.refund.reason, ledgerId: row.refund.ledgerId } : null } }
  private sessionNumber() { return `LS-${new Date().getFullYear()}-${Date.now().toString(36).toUpperCase()}` }
  private hasBlockedWords(value: string) { return /\b(fuck|shit|bitch|cunt|nigger|whore)\b/i.test(value) }
  private redact(value: string) { return value.replace(/\b(fuck|shit|bitch|cunt|nigger|whore)\b/gi, "•••") }
}
