import { createHash } from "node:crypto"

const BOT_NAMES = [
  "Nova",
  "Atlas",
  "Pixel",
  "Echo",
  "Luna",
  "Bolt",
  "Sage",
  "Orion",
  "Maverick",
  "Zippy",
  "Cosmo",
  "Riley",
  "Ember",
  "Phoenix",
  "Comet",
  "Neko",
  "Titan",
  "Willow",
  "Aspen",
  "Jasper",
  "Hazel",
  "Clover",
  "Storm",
  "Sunny",
  "River",
  "Skye",
  "Blaze",
  "Scout",
  "Maple",
  "Dakota",
  "Finley",
  "Piper",
  "Quinn",
  "Rowan",
  "Sable",
  "Indigo",
  "Marlowe",
  "Zephyr",
  "Nimbus",
  "Astro",
  "Rocket",
  "Viper",
  "Falcon",
  "Lynx",
  "Panda",
  "Koda",
  "Mochi",
  "Kiwi",
  "Wren",
  "Iris",
  "Onyx",
  "Opal",
  "Jade",
  "Ruby",
  "Coral",
  "Azure",
  "Flint",
  "Copper",
  "Silver",
  "Goldie",
  "Orbit",
  "Vertex",
  "Matrix",
  "Vector",
  "Cipher",
  "Byte",
  "Kernel",
  "Turbo",
  "Dash",
  "Drift",
  "Racer",
  "Ace",
  "Champ",
  "Legend",
  "Hero",
  "Genius",
  "Brainy",
  "Whiz",
  "Puzzle",
  "Riddle",
  "Trivia",
  "Mathix",
  "Quizzy",
  "Thinker",
  "Clever",
  "Bright",
  "Focus",
  "Swift",
  "Rapid",
  "Flash",
  "Glow",
  "Spark",
  "Frost",
  "Breeze",
  "Thunder",
  "Lightning",
  "Rain",
  "Misty",
  "Ocean",
  "Summit",
] as const

/**
 * Gives each bot a human-readable name that is random-looking but stable for
 * the lifetime of a match. The name is derived on the server so every client
 * and the admin console render the same identity.
 */
export function botDisplayName(matchId: string, participantId: string) {
  const digest = createHash("sha256").update(`${matchId}:${participantId}`).digest()
  const name = BOT_NAMES[digest.readUInt32BE(0) % BOT_NAMES.length]
  const suffixLength = 3 + (digest[4] % 8)
  const minimum = 10n ** BigInt(suffixLength - 1)
  const range = 9n * minimum
  const suffix = (minimum + digest.readBigUInt64BE(5) % range).toString()
  return `${name}${suffix}`
}
