import { Module } from "@nestjs/common"

import { DatabaseModule } from "./database/database.module"
import { HealthController } from "./health.controller"
import { NotesController } from "./notes.controller"
import { AuthModule } from "./modules/auth/auth.module"
import { PlayersModule } from "./modules/players/players.module"
import { SystemAdminModule } from "./modules/system-admin/system-admin.module"
import { ProgressionModule } from "./modules/progression/progression.module"
import { EconomyModule } from "./modules/economy/economy.module"
import { LeaderboardModule } from "./modules/leaderboard/leaderboard.module"
import { GameModule } from "./modules/game/game.module"
import { MatchesModule } from "./modules/matches/matches.module"
import { CommerceModule } from "./modules/commerce/commerce.module"
import { StorageModule } from "./modules/storage/storage.module"
import { FriendsModule } from "./modules/friends/friends.module"
import { MatchmakingModule } from "./modules/matchmaking/matchmaking.module"
import { ConfigModule } from "./modules/config/config.module"
import { AdRewardsModule } from "./modules/ad-rewards/ad-rewards.module"
import { NotificationsModule } from "./modules/notifications/notifications.module"
import { RealtimeModule } from "./modules/realtime/realtime.module"
import { AdMobModule } from "./modules/admob/admob.module"
import { GldModule } from "./modules/gld/gld.module"
import { GiftsModule } from "./modules/gifts/gifts.module"
import { ReferralsModule } from "./modules/referrals/referrals.module"
import { RankingModule } from "./modules/ranking/ranking.module"
import { MissionsModule } from "./modules/missions/missions.module"
import { FraudModule } from "./modules/fraud/fraud.module"
import { StreaksModule } from "./modules/streaks/streaks.module"
import { ChatsModule } from "./modules/chats/chats.module"
import { SupportModule } from "./modules/support/support.module"
import { CooperativeModule } from "./modules/cooperative/cooperative.module"
import { WinStreaksModule } from "./modules/win-streaks/win-streaks.module"
import { DailyChallengesModule } from "./modules/daily-challenges/daily-challenges.module"
import { GemBlitzModule } from "./modules/gem-blitz/gem-blitz.module"

@Module({
  imports: [DatabaseModule, AuthModule, EconomyModule, LeaderboardModule, GameModule, MatchesModule, MatchmakingModule, PlayersModule, ProgressionModule, CommerceModule, StorageModule, FriendsModule, ConfigModule, AdRewardsModule, NotificationsModule, SystemAdminModule, RealtimeModule, AdMobModule, GldModule, GiftsModule, ReferralsModule, RankingModule, MissionsModule, FraudModule, StreaksModule, WinStreaksModule, ChatsModule, SupportModule, CooperativeModule, DailyChallengesModule, GemBlitzModule],
  controllers: [HealthController, NotesController],
})
export class AppModule {}
